name: PC Virtual
on:
  workflow_dispatch: {}

jobs:
  rodar:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Exibir mensagem da Máquina Virtual
        run: |
          echo "✅ PC-Virtual-01 LIGADA com sucesso!"
          echo "💻 Sistema: Ubuntu 22.04"
          echo "🧠 RAM: 8 GB"
          echo "💾 Disco: 256 GB"
          echo "🎉 Tudo funcionando PERFEITAMENTE!"
          echo "🔌 PC-Virtual-01 DESLIGADA"
          
          
