name: PC Virtual
on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Meu PC Virtual
        run: |
          echo "================================"
          echo "✅ PC-Virtual-01 LIGADA!"
          echo "💻 Sistema: Ubuntu 22.04"
          echo "🧠 Memória: 8 GB RAM"
          echo "💾 Armazenamento: 256 GB"
          echo "================================"
          echo "🎉 FUNCIONOU PERFEITAMENTE!"
          echo "================================"
